In [1]:
import numpy as np 
import torch

/Users/openknowl/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### 1D Array With NumPy

In [2]:
t = np.array([0,1,2,3,4,5,6])
t

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [4]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


### 2D Array With NumPy

In [7]:
t = np.array([[1., 2.,3.],
              [4.,5.,6.],
              [7.,8.,9.,],
             [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  2
Shape of t :  (4, 3)


### 1D Array with PyTorch

In [9]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


### 2D Array With PyTorch 

In [12]:
t = torch.FloatTensor([[1., 2.,3.],
              [4.,5.,6.],
              [7.,8.,9.,],
             [10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [13]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


In [15]:
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [17]:
# same shape 
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [19]:
# vector + scaler 
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # -> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [24]:
# 2 X 1 vector + 1 X 2 scaler 
m1 = torch.FloatTensor([[1,2]]) # -> [1,2][1,2]
m2 = torch.FloatTensor([[3],[4]]) # -> [3,3],[4,4]
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [23]:
# 2 X 2 vector + 2 X 3 scaler 
m1 = torch.FloatTensor([[1,1],
                       [1,1]]) 
m2 = torch.FloatTensor([[3,3],
                        [4,4],
                        [5,5]])
print(m1+m2)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

## Multiplication vs. Matrix Multiplication 

In [26]:
# 행렬곱
m1 = torch.FloatTensor([[1,2],
                       [3,4]]) # 2x2 
m2 = torch.FloatTensor([[1],[2]]) # 2x1
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [27]:
print(m1*m2)

tensor([[1., 2.],
        [6., 8.]])


### Mean , Sum

In [31]:
t = torch.FloatTensor([[1,2],
                      [3,4]])

In [32]:
t.mean()

tensor(2.5000)

In [33]:
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [34]:
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [35]:
print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [36]:
print('Max' , t.max(dim=0)[0])
print('ArgMax' , t.max(dim=0)[1])

Max tensor([3., 4.])
ArgMax tensor([1, 1])
