# 다항 회귀 ( Polynomial Regression )

#### (x1, x2) 의 단항값을 2차 다항값으로 변환 예제

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(4).reshape(2,2)
X

array([[0, 1],
       [2, 3]])

In [2]:
# degree = 2 
poly = PolynomialFeatures(degree = 2)
poly.fit(X)
poly_ftr = poly.transform(X)
poly_ftr

array([[1., 0., 1., 0., 0., 1.],
       [1., 2., 3., 4., 6., 9.]])

In [4]:
# 3차 다항식 값만 반환 함수 

def polynomial_func(X):
    y =1 + 2*X + X**2 + X**3
    return y

y = polynomial_func(X)
y

array([[ 1,  5],
       [17, 43]])

In [5]:
# 3차 다항식 변환 

ploy_ftr =PolynomialFeatures(degree =3).fit_transform(X)
ploy_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(ploy_ftr, y)

print('Polynomial 회귀 계수 \n', np.round(model.coef_, 2))
print('Polynomial 회귀 shape \n', model.coef_.shape)

Polynomial 회귀 계수 
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
Polynomial 회귀 shape 
 (2, 10)


In [8]:
# 파이프 라인 활용 
from sklearn.pipeline import Pipeline

model = Pipeline([('poly', PolynomialFeatures(degree = 3)), ('linear', LinearRegression())])

model.fit(X, y )
print ('Polynomial 회귀 계수\n', np.round(model.named_steps['linear'].coef_, 2))

Polynomial 회귀 계수
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
